[tool.poetry]
name = "exploit"
version = "0.1.0"
description = ""
authors = ["cristiandrami <cristiandramisino@libero.it>"]

[tool.poetry.dependencies]
python = "^3.10"
rich = "^13.6.0"
typer = "^0.9.0"
requests = "^2.31.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
